### ISSUE TITLE
Docker image doesn't save new bees.

### ISSUE THREAD

**Issue by sgama** [muesli/beehive#249]
I'm trying to set up Beehive on my server but I can't seem to get it to save the Cron or Twitter bee.
Here's my docker-compose file:

```
version: "3.5"

services:
  beehive:
    container_name: beehive
    hostname: beehive
    image: fribbledom/beehive:latest
    expose:
      - 8181
    environment:
      - CANONICAL_URL=http://localhost:8181/
    ports:
      - 8181:8181
    restart: always
    volumes:
      - beehive_data:/conf

volumes:
  beehive_data:
    name: beehive_data
```

The docker logs don't seem to show any error. 
Process to reproduce:
- Create a new bee, save
- Clear browser cache (Control-shift-R) and reload

No bees are available. Checking /conf/beehive.conf shows a JSON file with these contents:
```
{
  "Bees": [],
  "Actions": null,
  "Chains": []
}
```

Let me know if I can provide any additional clarifications or if you require any help with the docker-compose file.
